---
cog_bundle_version: 3
name: statuspage
version: 0.1.0
# docker:
#   image: cogcmd/statuspage
#   tag: 0.1
commands:
  component:
    executable: /Users/kevsmith/repos/work/cog-bundles/dev/bin/cog-command
    documentation: |
      Enumerate and view status of defined statuspage.io components

      statuspage:component [list*|status]  *=default
    rules: [ 'allow' ]
  incident:
    executable: /Users/kevsmith/repos/work/cog-bundles/dev/bin/cog-command
    documentation: |
      List, create, and update statuspage.io incidents

      statuspage:incident list
      statuspage:incident new [-s|--status] [-i|--impact] [-c|--component] [-n|--name] [message]
      statuspage:incident update [-s|--status] [-i|--impact] [-c|--component] [-n|--name] [message]
    rules: [ 'allow' ]
    options:
      all:
        type: bool
        required: false
        short_flag: a
      status:
        type: string
        required: false
        short_flag: s
      impact:
        type: string
        required: false
        short_flag: i
      component:
        type: string
        required: false
        short_flag: c
      name:
        type: string
        required: false
        short_flag: n
    rules: [ 'allow' ]
templates:
  comps_list:
    slack: |
      {{name}}
  comps_status:
    slack: |
      Component: {{name}}  Status: {{status}}  Last Updated: {{last_updated}}
  incidents_list:
    slack: |
      Incident {{name}} ({{impact}}) has been active since {{active_since}}. Current status is '{{status}}'.
      {{link}}
  no_incidents:
    slack: "{{incidents}} unresolved incidents found."
  incident_created:
    slack: |
      Incident {{name}} was created. Click {{link}} to view.
  incident_updated:
    slack: |
      Incident {{name}} was updated. Click {{link}} to view.
  incident_resolved:
    slack: |
      Incident {{name}} was resolved at {{resolved_at}}. Click {{link}} to view.

