---
cog_bundle_version: 4
name: statuspage
description: Interact with the statuspage.io API
version: 0.1.6
docker:
  image: cogcmd/statuspage
  tag: 0.1.5
permissions:
  - statuspage:update
commands:
  component:
    executable: /usr/bin/cog-command
    description: Enumerate and view status of defined components
    documentation: |
      Enumerate and view status of defined statuspage.io components

      statuspage:component [list*|status]  *=default
    rules: [ 'allow' ]
  incident:
    executable: /usr/bin/cog-command
    description: List, create, and update incidents
    documentation: |
      List, create, and update statuspage.io incidents

      statuspage:incident list
      statuspage:incident new [-s|--status] [-i|--impact] [-c|--component] [-n|--name] [message]
      statuspage:incident update [-s|--status] [-i|--impact] [-c|--component] [-n|--name] [message]
    rules:
      - 'when command is statuspage:incident must have statuspage:update'
    options:
      all:
        type: bool
        required: false
        short_flag: a
      status:
        type: string
        required: false
        short_flag: s
      impact:
        type: string
        required: false
        short_flag: i
      component:
        type: string
        required: false
        short_flag: c
      name:
        type: string
        required: false
        short_flag: n
    rules: [ 'allow' ]
templates:
  comps_list:
    body: |
      ~each var=$results as=result~
      ~$result.name~
      ~end~
  comps_status:
    body: |
      ~each var=$results as=result~
      Component: ~$result.name~  Status: ~$result.status~  Last Updated: ~$result.last_updated~
      ~end~
  incidents_list:
    body: |
      ~each var=$results as=result~
      Incident ~$result.name~ (~$result.impact~) has been active since ~$result.active_since~. Current status is '~$result.status~'.
      ~$result.link~
      ~end~
  no_incidents:
    body: |
      ~each var=$results as=result~
      "~$result.incidents~ unresolved incidents found."
      ~end~
  incident_created:
    body: |
      ~each var=$results as=result~
      Incident ~$result.name~ was created. Click ~$result.link~ to view.
      ~end~
  incident_updated:
    body: |
      ~each var=$results as=result~
      Incident ~$result.name~ was updated. Click ~$result.link~ to view.
      ~end~
  incident_resolved:
    body: |
      ~each var=$results as=result~
      Incident ~$result.name~ was resolved at ~$result.resolved_at~. Click ~$result.link~ to view.
      ~end~

